Database:
  Host: 'localhost'
  Port: 3306
  User: 'root'
  Password: '123'
  Base: 'basictools'

Panel:
  PanelInventory:
    Title: 'Panel Inventory'
    Template:
      - 'xxxxxxxxx'
      - 'xabcdefgx'
      - 'xhijklmnx'
      - 'xoprstuwx'
      - 'x1234567x'
      - 'xxxxxxxxx'
    TemplateExplanation:
      - 'x:BLACK_STAINED_GLASS_PANE'
    CommandTemplate:
      Name: 'Polecenie {NAME}'
      Lore:
        - 'Kliknij, by wykonać.'
        - ' '
        - 'Nazwa: {NAME}'
        - 'Użycie: {USAGE}'
        - 'Uprawnienie: {PERMISSION}'
        - 'Masz dostęp: {ACCESS}'
  ArgumentsInventory:
    Title: 'Argumenty: {NAME}'
    DefaultText: 'Wpisz argumenty'
    PaperTemplate:
      Lore:
        - 'Wpisz argumenty!'
        - 'Nazwa komendy: {NAME}'
        - 'Użycie: {USAGE}'
GroupsInListCommand:
  - 'root:&4ROOT'
  - 'admin:&cAdmin'
  - 'mod:&aModerator'
  - 'default:&7Gracz'